name: Deploy Backend to Heroku

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build (if needed)
        working-directory: ./backend
        run: npm run build || echo "No build step"

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token
          heroku git:remote --app sr-admin-backend

      - name: Deploy backend (subtree push)
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git fetch
          git subtree push --prefix backend https://heroku:$HEROKU_API_KEY@git.heroku.com/sr-admin-backend.git master
